apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j5vlgo8lj-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:be41e606174acf07364b711caf51ea51fa0354db@sha256:0ca8b2c186b8fb0dc9a833a4cd78a4e1f498ab2e72ddc5616dad71bd3bd5d7b1
          name: container-image
